Module7 task1
htmlacademy-ecmascript/1263893-cinemaddict-14 pull request #10
Opened 2021-05-13 10:47 UTC by hawkf

2021-05-13 14:08 UTC, Shv-sergey70 requested changes

2021-05-13 14:08 UTC, Shv-sergey70 commented on src/presenter/moviePresenter.js
> +export default class MoviePresenter {
Название файла презентера НЕ должен быть в camelCase

2021-05-13 14:08 UTC, Shv-sergey70 commented on src/view/no-film.js
> +};
Эту разметку не нужно выносить за пределы класса. Оставь ее в `getTemplate`, потому что она маленькая

2021-05-13 14:08 UTC, Shv-sergey70 commented on src/model/filter.js
> +  }
Называть методы в моделях можно просто `set`, `get`, `update` и тд. Без дублирования в названии метода названия класса

2021-05-16 19:08 UTC, Shv-sergey70 requested changes

2021-05-16 19:08 UTC, Shv-sergey70 commented on src/presenter/popup.js
> +  }
А где это используется?

2021-05-16 19:08 UTC, Shv-sergey70 commented on src/presenter/popup.js
> +  _delateCommentHandler(commentIndex) {
`_delateCommentHandler` -> `_deleteCommentHandler`

2021-05-16 19:08 UTC, Shv-sergey70 commented on src/presenter/popup.js
> +    if(prevFilmInformationComponent === null) {
После if, но перед открывающей скобкой нужен пробел

2021-05-16 19:08 UTC, Shv-sergey70 commented on src/view/comments.js
> +    document.addEventListener('keydown', this._formSubmitHandler);
Я думаю что баг, о котором ты писал мне в ЛС связан с этим местом. Ты добавляешь тут обработчик и при каждом вызове `init` метода этот код снова вызывается, таким образом на документ вешается все больше и больше обработчиков, при этом они не снимаются автоматически, потому что документ существует на протяжении всего времени работы приложения

2021-05-16 20:35 UTC, hawkf commented on src/presenter/popup.js
> +  }
_renderMovieList() {
    const filmCount = this._getMovies().length;
    this._filmsListContainerElement = this._filmsListComponent.getElement().querySelector('.films-list__container');
    const films = this._getMovies();

    if(this._renderedMoviePresenter !== null) {
      const popupFilm = films.find((film) => film.id === this._renderedMoviePresenter.getFilmId());
      this._renderedMoviePresenter.update(popupFilm);
      this._renderedMoviePresenter.init();
    }

код из movie-list-presenter

2021-05-18 16:21 UTC, merged